CREATE TABLE memory_general (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_name TEXT NOT NULL UNIQUE,
    player_created TIMESTAMP NOT NULL DEFAULT now(),
    total_time_played TIME NOT NULL,
);