CREATE TABLE memory_user (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quickest_game_played TIME,
    experience_level TEXT,
    background_theme TEXT,
    card_theme TEXT
);

ALTER TABLE memory_general
    ADD COLUMN
        player_id INTEGER REFERENCES memory_user(id)
        ON DELETE SET NULL;